server:
  port: 9005

# 应用名称
spring:
  application:
    name: java-sharding-db-tables
  shardingsphere:
    # 参数配置，显示sql
    props:
      sql:
        show: true
    # 配置数据源
    datasource:
      # 给每个数据源取别名
      names: ds0,ds1
      ds0:
        # 配置druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url:
        username:
        password:
        maxPoolSize: 100
        minPoolSize: 5
      # 配置读库
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url:
        username:
        password:
        maxPoolSize: 100
        minPoolSize: 5
    sharding:
      # 默认数据源
      default-data-source-name: ds0
      # 配置分表的规则
      tables:
        # 逻辑表名 user
        user:
          # 数据节点： 数据源 $->{0..N}.逻辑表明$->{0..N} 这里采用的是groovy表达式来配置
          actual-data-nodes: ds$->{0..1}.user
          # 拆分库策略
          databaseStrategy:
            standard:
              shardingColumn: birthday
              preciseAlgorithmClassName: cn.java.sharding.standard.config.BirthdayAlgorithm

  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.java.sharding.standard.model




